Create a decorator for FormObject creation function
infinum/ngx-form-object pull request #56
Opened 2022-03-22 14:30 UTC by thabalija

2022-03-30 10:10 UTC, safo6m requested changes

2022-04-05 07:28 UTC, thabalija commented on docusaurus/docs/api-reference/decorators.md
> +### @BuildRelationshipFormObject(propertyName: string)
Added description:
`Requires relationship `propertyName` as an argument which must be equal to the property name defined in the model.`

2022-04-05 07:30 UTC, thabalija reviewed
Approved @safo6m  👍

2022-04-06 12:38 UTC, safo6m approved these changes

2022-04-06 12:39 UTC, merged